### ISSUE TITLE
Improve Search command runner 

### ISSUE THREAD

**Issue by LingJie-Zhu** [cs2103aug2015-w15-3j/main#105]
## Features
- [x] set head message to match search term and number of results 
- [x] search by matching subtoken 
- [x] includes usage of filter to further narrow down search result 
  - [x] using tag
  - [x] using priority

**Comment by tsoonjin** [comment]
@cs2103aug2015-w15-3j/developers 

Current search will only return true if it matches the keyword exactly. This is because user do not usually want partial match since it may return too many results 

Searching for  `att` will return nothing.
User would need to search for `attend`.

The keywords also need not follow the order. As long as the task contains all the keywords, it will return true 

Searching for `attend holland` will return true for task: 

> attend a wedding in holland
