### ISSUE TITLE
Collect Product Survey & Organise for Appendix C

### ISSUE THREAD

**Issue by tsoonjin** [cs2103aug2015-w15-3j/main#23]
Please organize them into the following format: 

Product name, Documented by [name of member],Strengths, Weaknesses

**Comment by tsoonjin** [comment]
Nitro
Documented by Tan Soon Jin 

Strengths: 
- ease of use. basic features are releatively obvious and does not require a lot of exploration
- minimalistic interface. It is not cluttered, and different buckets of todos are clearly separated at 
  the set making it easy to navigate between different buckets
- ability to add note to todo. it is very useful to record down details of certain todo i.e location while 
  not cluttering the title
- automatically show pending tasks for today. 
- can choose deadline easily from pop-up calendar.

Weaknessess: 
- ui is not very responsive. Requires the user to deselect the current todo by clicking on the 
  background
- marking todo as done does not remove task(need to click move completed tasks to logbook). This 
  is rather time wasting as most user who want to just get rid of the task from current view.
- ever growing list of completed tasks is not useful. A normal user would rarely scroll all through mountain of todos to find out what he/she completed last month
- cannot add specific timing as deadline. This forces the user to enter the deadline into the note
  section which is not visible in th view.

**Comment by LingJie-Zhu** [comment]
Habitica
Documented by Zhu Lingjie

Strengths: 
- Uses gamification to encourage users to plan their to-dos and their everyday habits. 
- The essential features are all on a single page and are easy to understand and use. 
- Contains social networking features for you to communicate with other users of the app.
- Has a very attractive GUI. 
- Contains unique features: Dailies- tasks that must be fulfilled every day else it minuses your experiences, and Habits- that help to add extra points if they are good for you, minus points if they aren't.

Weaknesses: 
- I NEED to login to use the app.
- Only available through a web browser!! 
- The extra features (like fighting a boss and getting a party member) are very difficult to figure out. Discourages users like me from trying further.
- There doesn't seem to be any automatic priority indicator for the to-dos. You have to manually order the to-dos by yourself.
- There is a two-step whenever I want to add a to-do. I need to enter the title first to create a task, and then after that I have to edit it if I want to add date. It could have been made simpler.

**Comment by leeyjj** [comment]
Todoist
Documented by Lee Ying Jie

Strengths:
- Very sleek and minimalistic interface and is quite intuitive to the user.
- Has the option to sort tasks by date, priority or name which is very convenient.
- Also has the option to add tasks below or above a certain task, and able to order the tasks whichever way I want.
- When adding a new task and setting a deadline, if I hovered over a particular date in the calendar, there is a column where I am able to view my scheduled tasks for that day.
- Had a very interesting feature. It had a graph which documented my productivity over the days and allowed me to earn “Karma points” in the software.

Weaknesses:
- I needed an account to use the software which is rather pointless since I neither wanted to sync my tasks to the cloud nor provide my email to the software.
- Certain icons were confusing and had no help text to show what the icons were for when the cursor hovers over it.
- Although the interface is minimalistic, it is inefficient has I had to make multiple clicks to open up the date menu to set a deadline for the task.
- Had no overview (a calendar view) of my tasks which would have been very helpful.
- I need to pay to be able to use the desktop notification feature, and to attach notes and files to the task.

**Comment by woanchin** [comment]
Any.do
Documented by Tee Woan Chin

Strengths:
1. Pop up notification is optional, this feature is quite nice.
1. Simple registration process.

Weaknesses:
1. When I finish a task, I'm given a tick option which helps me to cancel it out. But it doesn't show up in my completed tasks list. I only complete a task after I "delete" the task... Not intuitive?
1. No help guide explicitly provided. How to use certain features etc... How to use sync, what does it do? sync to what? 
2. Essential tasks like recurring tasks only available on Premium.
3. Limited to daily view... But sometimes having a monthly view is required -> plan long term stuff.
4. No desktop version available.
5. Things like change colour settings = only available on Premium :<
