### ISSUE TITLE
Add more information to error messages

### ISSUE THREAD

**Issue by LingJie-Zhu** [cs2103aug2015-w15-3j/main#59]
Need more information than just "Failed to parse %s"

Include the wrapped error messages perhaps? Gives the user more information on what he/she has typed wrongly.

**Comment by tsoonjin** [comment]
This is possible if parser can return a the specific input that is considered erroneus. The mechanism is already there.

**Comment by tsoonjin** [comment]
I believe it a better way is for the Simple Parser to include the details in the message instead of just returning message of child exception to provide context. It is not feasible to check for type of exception in the higher level exception. Then the if's statements will grow as the number of child exceptions grow.
